# Generated by Django 3.2.9 on 2021-11-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
