# Generated by Django 3.2.9 on 2021-11-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_auto_20211109_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='video_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
