# Generated by Django 3.2.9 on 2021-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0003_reply_video_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
