# Generated by Django 3.2.9 on 2021-11-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0004_comment_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video_pk',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='video_pk',
        ),
        migrations.AddField(
            model_name='reply',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
