# Generated by Django 3.2.9 on 2021-11-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0004_auto_20211111_1332'),
        ('youtubeapp', '0005_auto_20211111_1330'),
    ]

    operations = [
    ]
